#!/usr/bin/env python3
"""Factor and map the composite closed channel without changing physics."""
from pathlib import Path
import json,numpy as np,pandas as pd
from audit_zro2_forward_relative_property_bounds import make_states,TCS
from run_zro2_forward_resolved_rules import params
from zro2_forward.material_zro2 import R
from zro2_forward.resolved_rules import ResolvedRuleModel
OUT=Path("results/zro2_forward_closed_channel_apparent_law_correction");QPR=params().Q_PR_J_mol;TREF=params().T_PR_ref_K
def fit(T,r):
 mask=np.isfinite(r)&(r>0);T=np.asarray(T)[mask]+273.15;r=np.asarray(r)[mask]
 if len(r)<4:return np.nan,np.nan,np.nan,False,"insufficient_positive_rates"
 x=1/T;y=np.log(r);coef=np.polyfit(x,y,1);pred=np.polyval(coef,x);ss=((y-pred)**2).sum();tot=((y-y.mean())**2).sum();flat=tot<1e-20;return -R*coef[0]/1000,coef[1]/np.log(10),1. if flat else 1-ss/tot,True,"flat_after_normalization" if flat else ""
def factor_row(sid,path,TC,s,d):
 p=s.pores;phi=p.phi_closed.sum();A=s.A_closed;activity=d["activity_closed"];theta=np.exp(np.clip(-.35*QPR/R*(1/(TC+273.15)-1/TREF),-30,30));size=np.sum(p.phi_closed*(25e-9/p.radii_m)**4)/phi if phi>0 else np.nan;pref=1/params().closed_tau0_s;rate=d["rho_dot_closed_sinv"]
 factors={"inventory":phi/.1,"accommodation":A,"activity":activity,"size":size,"thermal":theta,"prefactor":pref/1e-3}
 if phi<=1e-14:lim="no_closed_inventory";val=phi;interp="no closed store exists"
 else:
  key=min(factors,key=lambda k:max(factors[k],0));lim={"inventory":"closed_inventory_not_shrinkable","accommodation":"accommodation_limited","activity":"activity_limited","size":"size_limited","thermal":"thermal_factor_limited","prefactor":"prefactor_limited"}[key];val=factors[key];interp=f"smallest normalized factor: {key}"
  if sum(v<.1 for v in factors.values())>1:lim="coupled_small_factors";interp="multiple normalized factors below 0.1"
 return {"state_id":sid,"path_id":path,"T_C":TC,"rho":s.rho,"phi_closed_total":phi,"shrinkable_closed_inventory":phi,"A_closed":A,"A_closed_capacity":params().accommodation_capacity_phi,"accommodation_factor":A,"activity_closed":activity,"availability_factor":d["closed_availability"],"size_factor":size,"thermal_factor":theta,"prefactor_or_rate_scale":pref,"rho_dot_closed":rate,"rho_dot_open":d["rho_dot_open_sinv"],"rho_dot_total":d["rho_dot_total_sinv"],"closed_fraction_of_density_rate":rate/max(d["rho_dot_total_sinv"],1e-300),"limiting_factor_name":lim,"limiting_factor_value":val,"limiting_factor_interpretation":interp,"analysis_only":True}
def main():
 OUT.mkdir(parents=True,exist_ok=True);states,_=make_states();m=ResolvedRuleModel(parameters=params());raw=[];factors=[]
 for sid,s in states.items():
  for TC in TCS:
   *_,d=m.rates(s,TC+273.15);phi=s.pores.phi_closed.sum();base={"state_id":sid,"path_id":"representative_state","T_C":TC,"rho":s.rho,"phi_closed_total":phi,"A_closed":s.A_closed,"activity_closed":d["activity_closed"],"rho_dot_closed":d["rho_dot_closed_sinv"]};raw.append(base);factors.append(factor_row(sid,"representative_state",TC,s,d))
 raw=pd.DataFrame(raw);slopes=[]
 modes=[("raw_closed_density_rate",lambda g:g.rho_dot_closed,"rho_dot_closed","s^-1 density"),("inventory_normalized",lambda g:g.rho_dot_closed/g.phi_closed_total,"rho_dot_closed / phi_closed_total","s^-1"),("inventory_accommodation_normalized",lambda g:g.rho_dot_closed/(g.phi_closed_total*g.A_closed),"rho_dot_closed / (phi_closed_total * A_closed)","s^-1"),("inventory_accommodation_activity_normalized",lambda g:g.rho_dot_closed/(g.phi_closed_total*g.A_closed*g.activity_closed),"rho_dot_closed / (phi_closed_total * A_closed * activity_closed)","s^-1")]
 for sid,g in raw.groupby("state_id"):
  for mode,fn,definition,units in modes:
   if g.phi_closed_total.max()<=1e-14:Q,lp,r2,ok,why=np.nan,np.nan,np.nan,False,"not_estimable_zero_inventory"
   elif "accommodation" in mode and g.A_closed.max()<=1e-14:Q,lp,r2,ok,why=np.nan,np.nan,np.nan,False,"not_estimable_zero_accommodation"
   elif "activity" in mode and g.activity_closed.max()<=1e-14:Q,lp,r2,ok,why=np.nan,np.nan,np.nan,False,"not_estimable_zero_activity"
   else:Q,lp,r2,ok,why=fit(g.T_C,fn(g))
   slopes.append({"state_id":sid,"path_id":"representative_state","T_range_C":f"{g.T_C.min():.0f}-{g.T_C.max():.0f}","rho_range":f"{g.rho.min():.6g}-{g.rho.max():.6g}","phi_closed_range":f"{g.phi_closed_total.min():.6g}-{g.phi_closed_total.max():.6g}","A_closed_range":f"{g.A_closed.min():.6g}-{g.A_closed.max():.6g}","activity_range":f"{g.activity_closed.min():.6g}-{g.activity_closed.max():.6g}","rate_quantity_used":definition,"normalization_mode":mode,"fit_equation":"Q_closed_app = -R * d ln(k_closed_app) / d(1/T)","Q_closed_app_kJ_mol":Q,"log10_prefactor_app":lp,"R2":r2,"slope_valid":ok,"reason_if_invalid":why,"diagnostic_only":True,"not_material_property":True,"rate_units":units})
 pd.DataFrame(slopes).to_csv(OUT/"apparent_closed_channel_slope_derivation.csv",index=False);fac=pd.DataFrame(factors);fac.to_csv(OUT/"closed_channel_factor_decomposition.csv",index=False)
 fac.groupby("limiting_factor_name").agg(point_count=("state_id","size"),median_value=("limiting_factor_value","median"),median_closed_rate=("rho_dot_closed","median")).reset_index().to_csv(OUT/"closed_channel_limiting_factor_summary.csv",index=False)
 status=[("Q_closed_app","apparent diagnostic only","should not be optimized directly"),("k_closed_prefactor","empirical optimizable parameter","only in explicitly empirical branch"),("closed_inventory_fraction","physically derivable but not yet implemented","measure/evolve by microstructure law"),("shrinkable_closed_fraction","physically derivable but not yet implemented","measure or derive"),("closed_pore_radius","known physical input","measure/evolve"),("radius_exponent","physically derivable but not yet implemented","derive from transport law"),("A_closed_max","empirical optimizable parameter","bounded proxy with caveat"),("A_closed_recovery_rate","empirical optimizable parameter","measure or bounded fit"),("accommodation_usage_factor","physically derivable but not yet implemented","derive/measure"),("gas_pressure_factor","physically derivable but not yet implemented","requires trapped-gas model"),("D_eff_choice","physically derivable but not yet implemented","derive; do not optimize"),("activity_closed_coupling","physically derivable but not yet implemented","derive from serial cycle"),("closed/open handoff threshold","empirical optimizable parameter","only empirical prototype"),("precursor_to_closed_rate","empirical optimizable parameter","measure/evolve"),("closed_shrinkage_rate_scale","empirical optimizable parameter","analysis only until explicit empirical branch")]
 pd.DataFrame(status,columns=["parameter","status","optimization_rule"]).to_csv(OUT/"closed_channel_parameter_status.csv",index=False)
 laws=[("GB_diffusion_closed_shrinkage","GB-diffusion-controlled closed-pore shrinkage",True,"removal","D_GB","Q_GB",380,"3 or 4","law-dependent","phi_closed,A_closed,r,sigma_eff","3D pore radius, stress/accommodation","gas/connectivity omitted",True),("surface_shape_accommodation","surface-diffusion-controlled shape accommodation",False,"conservative unless coupled","D_s","Q_s",380,4,"law-dependent","A_closed,r","pore shape relaxation","must not count as density alone",True),("renewal_limited_closed_shrinkage","serial renewal-limited closed shrinkage",True,"removal","GB/surface/lattice candidate","stress-resolved Gstar plus transport",np.nan,"geometry-dependent","eps_closed/tau_cycle","closed stress and geometry","mapping underdetermined",True),("gas_accommodation_limited","gas/accommodation-limited shrinkage",True,"removal","transport law required","transport plus pressure",np.nan,"law-dependent","P_capillary,P_gas,A_closed","trapped gas/pressure","new state variables",True),("empirical_reduced_closure","empirical reduced closed-channel closure",True,"removal","empirical","Q_closed_emp (not material property)",np.nan,"fitted","k0 units chosen for density rate","phi_closed,A_closed,r","trajectory calibration","empirical only",False)]
 L=pd.DataFrame(laws,columns=["law_id","description","density_changes_directly","conservative_or_removal","D_eff_source","activation_energy_source","expected_Q_kJ_mol","radius_exponent","dimensional_prefactor_units","state_variables_required","measurements_required","risk","recommended_for_next_implementation"]);L["validation_status"]="registry only; not installed; not validation";L.to_csv(OUT/"closed_channel_candidate_law_registry.csv",index=False)
 two=pd.read_csv("results/zro2_forward_open_closed_rate_handoff_audit/two_step_handoff_path_summary.csv");fx=pd.read_csv("results/zro2_forward_open_closed_rate_handoff_audit/two_step_handoff_flux_integrals.csv");req=[]
 for mode in ["resolved_default","candidate_state_injection_diagnostic"]:
  for _,r in two[two.mode_id.eq(mode)].iterrows():
   z=fx[(fx.mode_id.eq(mode))&(fx.path.eq(r.path))].iloc[0];openonly=.66+z.Delta_rho_open;need=max(0,.976-openonly);actual=z.Delta_rho_closed;factor=need/max(actual,1e-12);cls="order_unity" if .3<=factor<=3 else "moderate" if factor<=30 else "large" if factor<=1000 else "extreme"
   req.append({"path_id":f"{mode}:{r.path}","T2_C":r.T2_C,"rho_target":.976,"rho_final":r.final_rho,"G_final_nm":r.final_G_um*1000,"classification":r.classification,"actual_closed_density_gain":actual,"required_closed_density_gain":need,"current_mean_closed_rate":actual/(40*3600),"required_mean_closed_rate":need/(40*3600),"required_closed_rate_factor":factor,"factor_class":cls,"interpretation":"analysis only; multiplier not applied"})
 req=pd.DataFrame(req);req.to_csv(OUT/"required_closed_rate_magnitude.csv",index=False)
 base=req[req.path_id.str.startswith("resolved_default")];risk=[]
 for mult in (1,3,10,30,100,300,1000):
  attained={r.path_id.split(":")[-1]:.66+float(fx[(fx.mode_id.eq("resolved_default"))&(fx.path.eq(r.path_id.split(":")[-1]))].Delta_rho_open.iloc[0])+mult*r.actual_closed_density_gain>=.976 for _,r in base.iterrows()};low=attained["low_T2"];mid=attained["near_best"];high=attained["high_T2"];lower=not low;upper=True;mid_growth_ok=bool(two[(two.mode_id.eq("resolved_default"))&(two.path.eq("near_best"))].grain_ok.iloc[0]);finite=lower and mid and mid_growth_ok and upper;universal=all(attained.values());label="universal_density_success" if universal else "still_growth_limited" if mid and not mid_growth_ok else "helps_density_preserves_lower_boundary" if mid and lower else "helps_density_loses_lower_boundary" if mid and not lower else "no_effect"
  risk.append({"multiplier":mult,"low_T2_density_attained":low,"intermediate_T2_density_attained":mid,"high_T2_density_attained":high,"lower_boundary_preserved":lower,"upper_boundary_preserved":upper,"finite_window_possible":finite,"risk_of_universal_density_success":universal,"risk_of_losing_lower_boundary":not lower,"classification":label,"analysis_only":True})
 pd.DataFrame(risk).to_csv(OUT/"closed_prefactor_boundary_risk.csv",index=False)
 cr=Path("results/audit_candidate_693168_closed_accommodation");s=pd.read_csv(cr/"candidate_693168_reproduction_summary.csv").query("run_label=='original_exact'").iloc[0];ch=pd.read_csv(cr/"dense_candidate_693168_histories.csv");cs=ch[ch.path_label.eq("success")];forward=two[(two.mode_id.eq("resolved_default"))&(two.path.eq("near_best"))].iloc[0];forwardfx=fx[(fx.mode_id.eq("resolved_default"))&(fx.path.eq("near_best"))].iloc[0]
 comp=pd.DataFrame([{"model":"resolved_forward","switch_density":.8,"switch_G_nm":np.nan,"closed_fraction_at_switch":.0757768,"A_closed_at_switch":.994638,"closed_density_gain_after_switch":forwardfx.Delta_rho_closed,"highT_reference_G_nm":2293.6,"two_step_density_gain":forward.final_rho-.66,"T2_success_band":"none","lower_boundary_cause":"density exhaustion / closed-rate limitation","upper_boundary_cause":"intrinsic growth","Q_closed_app_kJ_mol":"118-137 apparent only","log10_prefactor_app":np.nan,"status":"conditional forward diagnostic, not validation"},{"model":"candidate_693168","switch_density":s.exact_switch_density,"switch_G_nm":s.G1_nm,"closed_fraction_at_switch":s.closed_fraction_at_switch,"A_closed_at_switch":s.closed_accommodation_at_switch,"closed_density_gain_after_switch":cs.cumulative_closed_pore_removed.iloc[-1],"highT_reference_G_nm":ch[ch.path_label.eq("highT_reference")].G_mean_nm.iloc[-1],"two_step_density_gain":cs.rho.iloc[-1]-s.exact_switch_density,"T2_success_band":s.success_T2_interval,"lower_boundary_cause":"closed accommodation density exhaustion","upper_boundary_cause":"grain growth","Q_closed_app_kJ_mol":"not estimated; different reduced layer","log10_prefactor_app":np.nan,"status":"conditional comparator, not validation"}]);comp.to_csv(OUT/"closed_channel_candidate693168_comparison.csv",index=False)
 print(pd.DataFrame(slopes).query("slope_valid").to_string(index=False));print(req.to_string(index=False))
if __name__=="__main__":main()
