#!/usr/bin/env python3
"""Extract selected fixed-physics cases and reconstruct dense histories only."""
from pathlib import Path
from dataclasses import replace
import json,numpy as np,pandas as pd
import run_zro2_forward_processing_window_prediction as src
from zro2_forward.conditioned_950c import run_path
from zro2_forward.schedules import RampHold,Iso
BASE=Path("results/zro2_forward_processing_window_prediction_figures");OUT=Path("results/zro2_forward_final_summary_figures")
def dense(frame,fig,path,path_type,case):
 x=src.history_frame(frame,dict(run_id=path,case_id=case,initial_state_id="S03276" if case=="P001" else "S00579",schedule_id=path,path_type=path_type));x.insert(0,"figure_id",fig);x.insert(1,"panel_id","A-F");x.insert(3,"path_label",path);x["densification_rate"]=x.rho_dot_total;x["sigma_eff_MPa"]=x.sigma_eff/1e6;return x
def first_frame(rows):
 x=pd.DataFrame(rows).rename(columns={"G_nm":"G_m"});x.G_m*=1e-9;return x
def main():
 OUT.mkdir(parents=True,exist_ok=True);(OUT/"figures_main").mkdir(exist_ok=True);(OUT/"figures_supplement").mkdir(exist_ok=True);(OUT/"source_tables").mkdir(exist_ok=True)
 resolution={"run_state.json":"run_state.json","fixed_zro2_parameter_manifest.csv":"fixed_zro2_parameter_manifest.csv","prior_solution_reference_manifest.csv":"prior_solution_manifest.csv","heating_rate_histories.csv":"heating_rate_histories.csv","heating_rate_matched_density_ratios.csv":"heating_rate_matched_density_ratios.csv","heating_rate_benefit_summary.csv":"prediction_outcome_summary.csv","heating_rate_selected_cases.csv":"selected_representative_cases.csv","twostep_second_step_classification_points.csv":"twostep_second_step_classification_points.csv","twostep_window_boundaries.csv":"twostep_window_boundaries.csv","twostep_boundary_gap_summary.csv":"twostep_boundary_gap_summary.csv","twostep_vs_isothermal_matched_density_ratios.csv":"twostep_vs_isothermal_matched_density_ratios.csv","twostep_selected_cases.csv":"selected_representative_cases.csv","refined_twostep_classification_points.csv":"twostep_second_step_classification_points.csv","refined_twostep_window_boundaries.csv":"twostep_window_boundaries.csv","refined_selected_case_histories.csv":"twostep_representative_histories.csv","selected_representative_cases.csv":"selected_representative_cases.csv","process_state_prediction_outcome_summary.csv":"prediction_outcome_summary.csv"}
 pd.DataFrame([dict(requested_file=k,resolved_file=v,source_directory=str(BASE),exists=(BASE/v).exists(),resolution_note="equivalent fixed-physics processing-window output") for k,v in resolution.items()]).to_csv(OUT/"source_file_resolution_manifest.csv",index=False)
 prom=pd.read_csv(BASE/"promoted_first_step_states.csv");p1=prom.query("case_id=='P001'").iloc[0];p14=prom.query("case_id=='P014'").iloc[0]
 # Heating reconstruction: fixed initial state/peak/hold; rate only varies.
 heat=[];select=[]
 for rate,role in [(.2,"slow/reference"),(1.,"intermediate"),(100.,"fast")]:
  f,h=run_path(src.model(),RampHold(rate,1500,0,start_C=950),src.initial(p1),60 if rate>=1 else 300,600,f"P001_{rate:g}");x=dense(h,"final_fig1",f"{rate:g} C/min","heating_rate","P001");heat.append(x);select.append(dict(case_id="P001",source_result_directory=str(BASE),figure_role=f"heating_{role}",initial_state_id=p1.initial_state_id,schedule_id=f"P001_1500C_0h_{rate:g}Cmin",T1_C=1500,T2_C=np.nan,heating_rate_C_min=rate,rho0=p1.rho0,G0_nm=p1.G0_nm,pore_D50_nm=p1.pore_D50_nm,rho_switch=np.nan,G1_nm=np.nan,classification="strong_fast_firing_response",finite_window_width_C=np.nan,reason_selected="best jointly attained matched-density separation; rate-only contrast",source_table="heating_rate_matched_density_ratios.csv",notes="fixed initial state, peak and zero hold"))
 heat=pd.concat(heat,ignore_index=True);heat.to_csv(OUT/"final_heating_rate_histories.csv",index=False);heat.to_csv(OUT/"final_heating_rate_panel_source.csv",index=False);heat.to_csv(OUT/"source_tables/final_fig1_heating_rate_response_source.csv",index=False)
 ratio=pd.read_csv(BASE/"heating_rate_matched_density_ratios.csv");r=ratio[(ratio.case_id=="P001")&(ratio.T_peak_C==1500)&(ratio.hold_h==0)&(ratio.reference_rate_C_min==.2)&ratio.fast_rate_C_min.isin([1,100])];r.to_csv(OUT/"final_heating_rate_summary.csv",index=False)
 # Exact stored first-step reconstruction, then selected low/central/high and comparator paths.
 first,fh,att=src.run_switch(type("R",(),p14.to_dict()),True);firstx=first_frame(fh);two=[]
 specs=[(850,"low T2 density failure","DENSIFICATION_EXHAUSTION_FAILURE","two_step"),(925,"central strict success","SUCCESS","two_step"),(1025,"high T2 growth failure","GRAIN_GROWTH_FAILURE","two_step"),(1500,"high-T isothermal comparator","COMPARATOR","high_T_isothermal")]
 for T,label,cl,typ in specs:
  f,h=run_path(src.model(),Iso(T,96),first,900,1800,f"P014_{T}");a=dense(firstx,"final_fig2",label,"first_step","P014");b=dense(h,"final_fig2",label,typ,"P014");x=pd.concat([a,b[b.physical_time_s>a.physical_time_s.max()]],ignore_index=True);two.append(x);select.append(dict(case_id="P014",source_result_directory=str(BASE),figure_role=label,initial_state_id=p14.initial_state_id,schedule_id=f"P014_T1_{p14.T1_C:g}_T2_{T}_96h",T1_C=p14.T1_C,T2_C=T,heating_rate_C_min=p14.rate_T1_C_min,rho0=p14.rho0,G0_nm=p14.G0_nm,pore_D50_nm=p14.pore_D50_nm,rho_switch=p14.rho_switch,G1_nm=p14.G1_nm,classification=cl,finite_window_width_C=125,reason_selected="largest strict Tier-like-B window and clean lower/success/upper ordering",source_table="twostep_window_boundaries.csv",notes="identical reconstructed first-step state; continuous physical time"))
 two=pd.concat(two,ignore_index=True);two.to_csv(OUT/"final_twostep_histories.csv",index=False);two.to_csv(OUT/"final_twostep_panel_source.csv",index=False);two.to_csv(OUT/"source_tables/final_fig2_twostep_vs_isothermal_response_source.csv",index=False)
 pts=pd.read_csv(BASE/"twostep_second_step_classification_points.csv");chen=pts[(pts.density_target==.90)&(pts.hold_h==96)&(pts.tolerance_tier=="Tier_like_B")].copy();bounds=pd.read_csv(BASE/"twostep_window_boundaries.csv");bb=bounds[(bounds.density_target==.90)&(bounds.hold_h==96)&(bounds.tolerance_tier=="Tier_like_B")][["case_id","lower_boundary_C","upper_boundary_C","finite_window"]];chen=chen.merge(bb,on="case_id",how="left");chen.to_csv(OUT/"final_chen_map_source.csv",index=False);chen.to_csv(OUT/"source_tables/final_fig3_standalone_chen_map_source.csv",index=False)
 pd.DataFrame(select).to_csv(OUT/"final_case_selection.csv",index=False)
 ts=two.groupby("path_label").tail(1)[["path_label","rho","G_nm","T_C","physical_time_h"]];ts["rho_target"]=.90;ts["switch_rho_actual"]=first.rho;ts["G1_nm"]=first.G_m*1e9;ts["finite_window_C"]="875-1000";ts.to_csv(OUT/"final_twostep_summary.csv",index=False)
 available=set(heat.columns)&set(two.columns);requested=set("figure_id panel_id case_id path_label path_type physical_time_s physical_time_h T_C rho G_nm G_um phi_open_total phi_iso_total phi_closed_total pore_D50_nm pore_D90_nm rho_dot_open rho_dot_closed rho_dot_total densification_rate cumulative_open_density_gain cumulative_closed_density_gain PR_memory PR_work A_closed_available A_closed_used A_closed_recovered activity Gstar_eV sigma_eff sigma_eff_MPa tau_nuc tau_exchange tau_transport tau_cycle Gamma_migration G_dot_intrinsic G_dot_actual mechanism_mode closed_law_mode mobility_case".split());pd.DataFrame([dict(field=x,status="unavailable in source diagnostics; not fabricated") for x in sorted(requested-available)]).to_csv(OUT/"missing_history_fields.csv",index=False)
 state=dict(branch="codex/zro2-forward-final-summary-figures",source_branch="codex/zro2-forward-processing-window-prediction-figures",source_commit="255446c",model_physics_changed=False,material_fitting=False,mobility_optimization=False,broad_search_run=False,selected_trajectory_reconstruction_only=True,heating_case="P001",twostep_case="P014",twostep_strict_success=True,finite_chen_window=True,validation=False);(OUT/"run_state.json").write_text(json.dumps(state,indent=2)+"\n");print(state)
if __name__=="__main__":main()
