#!/usr/bin/env python3
"""Create non-destructive companion tables correcting closed-channel terminology."""
from pathlib import Path
import hashlib,json,pandas as pd,numpy as np
OUT=Path("results/zro2_forward_closed_channel_apparent_law_correction");OLD=Path("results/zro2_forward_relative_property_bound_audit")
def main():
 OUT.mkdir(parents=True,exist_ok=True)
 pd.DataFrame([
  ("Q_closed","Q_closed_app","apparent closed-channel slope",False,"diagnostic only"),("Q_closed_eff","Q_closed_proxy","finite-difference emergent slope",False,"diagnostic only"),("closed activation barrier","apparent closed-channel coordinate","reduced composite coordinate",False,"diagnostic only"),("out-of-bound Q_closed","closed-channel mapping gap","failure to map physical inputs to reduced coordinate",False,"diagnostic interpretation"),("closed property gap","closed-channel rate/inventory/availability gap","model closure gap",False,"model closure gap")],columns=["old_term","new_term","meaning","use_as_physical_property","allowed_use"]).to_csv(OUT/"closed_channel_terminology_correction.csv",index=False)
 inherited=pd.DataFrame([
  ("relative audit physics","unchanged","no model physics changed"),("nucleation","stress-resolved G*(sigma,T)","fitted function evaluated at effective stress"),("GB diffusivity",380,"kJ/mol fixed"),("surface diffusivity",380,"kJ/mol fixed"),("growth branch",405.238,"kJ/mol high-temperature branch retained"),("mobility envelope",0,"all-gate cases"),("closed channel","primary unresolved group","mapping/rate/inventory/availability gap"),("prior closed slope language","apparent/proxy","not physical property")],columns=["evidence","value","interpretation"]);inherited["non_validation"]=True;inherited.to_csv(OUT/"inherited_relative_property_audit_summary.csv",index=False)
 reg=[
  ("Gstar_sigma_T","fitted_physical_function","ZrO2 barrier JSON","yes","stress-resolved function"),("Q_GB_380_kJ_mol","transferred_literature_input","ZrO2/ScSZ GB diffusivity paper","yes","physical transport input"),("Q_s_380_kJ_mol","transferred_literature_input","ZrO2/ScSZ surface diffusivity paper","yes","physical surface input"),("Q_growth_4p2_eV","transferred_literature_input","high-temperature 8YSZ mobility trend","yes_with_uncertainty","uncertain mobility branch"),("Q_PR_180_kJ_mol","reduced_model_coordinate","resolved PR closure","alternate_mapping_only","implemented reduced PR parameter"),("Q_closed_app_118_137_kJ_mol","apparent_model_coordinate","finite-difference closed-channel rate slope","no","emergent diagnostic only; not a material property"),("k_closed_eff","diagnostic_proxy","state-normalized closed rate","diagnostic_only","apparent rate coordinate"),("A_closed","diagnostic_proxy","bounded accommodation state","diagnostic_only","state variable / bounded proxy"),("closed_pore_fraction","diagnostic_proxy","evolving pore stores","diagnostic_only","evolving microstructure state"),("closed_channel_availability","diagnostic_proxy","instantaneous state function","diagnostic_only","evolving microstructure state/function")]
 pd.DataFrame(reg,columns=["quantity","registry_type","source","use_for_bound_audit","meaning"]).to_csv(OUT/"physical_vs_apparent_property_registry.csv",index=False)
 q=pd.read_csv(OLD/"relative_barrier_group_audit.csv").rename(columns={"Q_closed_eff_kJ_mol":"Q_closed_app_kJ_mol","Q_closed_eff_minus_Q_growth_kJ":"Q_closed_app_minus_Q_growth_reduced_coordinate_kJ","Q_PR_minus_Q_closed_eff_kJ":"Q_PR_minus_Q_closed_app_reduced_coordinate_kJ","Q_PR_separate_minus_Q_closed_eff_kJ":"Q_PR_separate_minus_Q_closed_app_reduced_coordinate_kJ","Q_closed_status":"Q_closed_app_status"})
 q["mapping_status"]="physical_comparison";mask=q.Q_closed_app_kJ_mol.notna();q.loc[mask,"mapping_status"]="apparent_proxy_only";q["closed_coordinate_classification"]=np.where(mask,"apparent_proxy_not_physical_property","mapping_unidentified")
 for c in [x for x in q if "inside_both_pass_closed" in x or "inside_both_pass_PR_closed" in x]:q.drop(columns=c,inplace=True)
 q.to_csv(OUT/"corrected_relative_barrier_group_audit.csv",index=False)
 p=pd.read_csv(OLD/"relative_prefactor_group_audit.csv").rename(columns={"log10_kclosed_over_kgrowth":"log10_kclosed_app_over_kgrowth","inside_log10_kclosed_over_kgrowth":"inside_reduced_kclosed_app_coordinate"});p["mapping_status"]=np.where(p.log10_kclosed_app_over_kgrowth.notna(),"apparent_proxy_only","mapping_unidentified");p["closed_rate_classification"]="apparent_proxy_not_physical_property";p.to_csv(OUT/"corrected_relative_prefactor_group_audit.csv",index=False)
 physical=["inside_both_pass_nuc_growth","inside_both_pass_nuc_PR","inside_both_pass_nuc_transport","inside_OAT_Delta_Q_nuc","inside_OAT_Delta_Q_growth","inside_PR_prefactor_threshold","inside_growth_prefactor_threshold"]
 f=q[["state_id","source","T_C"]+physical].copy();f["physical_input_classification"]=np.where(f[physical].all(axis=1),"physical_input_inside_range","physical_input_outside_range");f["closed_channel_mapping_status"]=np.where(q.Q_closed_app_kJ_mol.notna(),"apparent_proxy_only","mapping_unidentified");f["closed_channel_classification"]=np.where(q.Q_closed_app_kJ_mol.notna(),"apparent_proxy_not_physical_property","insufficient_state_support");f.to_csv(OUT/"corrected_statewise_property_window_classification.csv",index=False)
 pd.DataFrame([{"group":"trusted physical inputs","classification":"physical_input_inside_range","interpretation":"stress-resolved nucleation, GB/surface diffusion, and growth branch broadly compatible"},{"group":"resolved PR alternate","classification":"physical_input_uncertain","interpretation":"180 kJ/mol is reduced PR parameter; alternate mapping only"},{"group":"closed apparent slope","classification":"apparent_proxy_outside_reduced_coordinate","interpretation":"coordinate does not map cleanly; not physical pass/fail"},{"group":"closed rate magnitude","classification":"mapping_unidentified","interpretation":"inventory, prefactor, availability, and accommodation coupling unresolved"}]).to_csv(OUT/"corrected_property_mapping_summary.csv",index=False)
 state={"status":"complete_not_validated","model_physics_changed":False,"Q_closed_reclassified_as_apparent":True,"barrier_sha256":hashlib.sha256(Path("data/zro2/bicrystal_creep_barrier_export.json").read_bytes()).hexdigest(),"apparent_slope_not_material_property":True,"candidate_laws_installed":False,"validation_claim":False};(OUT/"run_state.json").write_text(json.dumps(state,indent=2)+"\n")
 print(f.to_string(index=False,max_rows=8))
if __name__=="__main__":main()
