#!/usr/bin/env python3
from pathlib import Path
import numpy as np,pandas as pd
import matplotlib.pyplot as plt
OUT=Path("results/zro2_forward_closed_channel_apparent_law_correction");FIG=OUT/"figures"
def save(fig,n):FIG.mkdir(parents=True,exist_ok=True);fig.suptitle("Closed-channel apparent-law correction — diagnostic, not validation",fontsize=10);fig.tight_layout(rect=[0,0,1,.96]);fig.savefig(FIG/f"{n}.png",dpi=180);fig.savefig(FIG/f"{n}.pdf");plt.close(fig)
def main():
 r=pd.read_csv(OUT/"physical_vs_apparent_property_registry.csv");fig,ax=plt.subplots(figsize=(11,5));types=pd.Categorical(r.registry_type);ax.scatter(types.codes,np.arange(len(r)),c=types.codes,cmap="tab10",s=90);ax.set(yticks=range(len(r)),yticklabels=r.quantity,xticks=range(len(types.categories)),xticklabels=types.categories);plt.setp(ax.get_xticklabels(),rotation=35,ha="right");save(fig,"physical_vs_apparent_property_map")
 q=pd.read_csv(OUT/"apparent_closed_channel_slope_derivation.csv");q=q[q.slope_valid];fig,ax=plt.subplots(figsize=(10,5));x=np.arange(len(q));ax.bar(x,q.Q_closed_app_kJ_mol);ax.set(xticks=x,xticklabels=q.state_id+"\n"+q.normalization_mode,ylabel="Q_closed_app (kJ/mol)");plt.setp(ax.get_xticklabels(),rotation=45,ha="right");save(fig,"apparent_Qclosed_derivation")
 f=pd.read_csv(OUT/"closed_channel_factor_decomposition.csv");g=f.groupby("state_id")[["phi_closed_total","accommodation_factor","activity_closed","size_factor","thermal_factor","prefactor_or_rate_scale"]].median();fig,ax=plt.subplots(figsize=(10,5));bottom=np.zeros(len(g));
 for c in g:vals=np.log10(np.maximum(g[c].to_numpy(),1e-12));ax.bar(g.index,vals,bottom=bottom,label=c);bottom+=vals
 ax.set_ylabel("stacked log10 factor magnitude");plt.setp(ax.get_xticklabels(),rotation=25,ha="right");ax.legend(fontsize=6);save(fig,"closed_channel_factor_stack")
 m=pd.read_csv(OUT/"required_closed_rate_magnitude.csv");fig,ax=plt.subplots(figsize=(11,5));x=np.arange(len(m));ax.bar(x-.2,m.current_mean_closed_rate,.4,label="current");ax.bar(x+.2,m.required_mean_closed_rate,.4,label="required");ax.set_yscale("log");ax.set(xticks=x,xticklabels=m.path_id,ylabel="mean closed density rate (s⁻¹)");plt.setp(ax.get_xticklabels(),rotation=40,ha="right");ax.legend();save(fig,"closed_rate_magnitude_gap")
 b=pd.read_csv(OUT/"closed_prefactor_boundary_risk.csv");fig,ax=plt.subplots();ax.semilogx(b.multiplier,b.low_T2_density_attained.astype(int),"o-",label="low T2");ax.semilogx(b.multiplier,b.intermediate_T2_density_attained.astype(int),"o-",label="intermediate T2");ax.semilogx(b.multiplier,b.high_T2_density_attained.astype(int),"o-",label="high T2");ax.set(xlabel="hypothetical multiplier (analysis only)",ylabel="density target attained");ax.legend();save(fig,"closed_prefactor_boundary_risk")
 c=pd.read_csv(OUT/"closed_channel_candidate693168_comparison.csv");fig,ax=plt.subplots(1,3,figsize=(11,4));ax[0].bar(c.model,c.closed_fraction_at_switch);ax[1].bar(c.model,c.A_closed_at_switch);ax[2].bar(c.model,c.closed_density_gain_after_switch);ax[0].set_ylabel("closed fraction at switch");ax[1].set_ylabel("accommodation at switch");ax[2].set_ylabel("closed density gain");[plt.setp(a.get_xticklabels(),rotation=20,ha="right") for a in ax];save(fig,"candidate693168_vs_forward_closed_channel")
 p=pd.read_csv(OUT/"closed_channel_parameter_status.csv");tab=pd.crosstab(p.status,p.optimization_rule);fig,ax=plt.subplots(figsize=(10,5));ax.imshow(tab>0,cmap="Blues",aspect="auto");ax.set(yticks=range(len(tab)),yticklabels=tab.index,xticks=range(len(tab.columns)),xticklabels=tab.columns);plt.setp(ax.get_xticklabels(),rotation=35,ha="right");save(fig,"next_decision_matrix")
if __name__=="__main__":main()
